# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
migrate_development:
  adapter: postgresql
  encoding: unicode
  database: iron_octopus
  pool: 1
  username: administrator
  password: administrator

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

development:
  adapter: postgresql
  encoding: unicode
  database: iron_octopus
  pool: 5
  username: application
  password: application

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  min_messages: log

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
migrate_test:
  adapter: postgresql
  encoding: unicode
  database: iron_octopus_test
  pool: 1
  username: administrator
  password: administrator
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

test: &test
  adapter: postgresql
  encoding: unicode
  database: iron_octopus_test
  pool: 5
  username: application
  password: application
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

migrate_production:
  adapter: postgresql
  encoding: unicode
  database: iron_octopus
  pool: 1
  username: administrator
  password: ADMIN_PASSWORD
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

production:
  adapter: postgresql
  encoding: unicode
  database: iron_octopus
  pool: 5
  username: application
  password: APPLICATION_PASSWORD
  host: localhost
  port: 5432
  schema_search_path: application,reporting,source,public

cucumber:
  <<: *test