# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

#users = User.create([
#                      { :login => 'system', :email => 'system@iron-octopus.com', :password => 'password' }
#                    ])

ActivityType.delete_all
Unit.delete_all
Metric.delete_all
BodyPart.delete_all
Implement.delete_all
ActivityAttribute.delete_all

ActivityType.create([
                      { :name => 'Calisthenics' },
                      { :name => 'Cardiovascular' },
                      { :name => 'Cycling' },
                      { :name => 'Olympic Lift' },
                      { :name => 'Pilates' },
                      { :name => 'Plyometric' },
                      { :name => 'Resistance' },
                      { :name => 'Sport' },
                      { :name => 'Stretch' },
                      { :name => 'Swimming' },
                      { :name => 'Yoga'}
                    ])

Metric.create([
                { :name => 'None'},
                { :name => 'Cadence'},
                { :name => 'Calories'},
                { :name => 'Distance'},
                { :name => 'Duration'},
                { :name => 'Incline'},
                { :name => 'Level'},
                { :name => 'Repetitions'},
                { :name => 'Resistance'},
                { :name => 'Speed'}
              ])

Unit.create([
              { :name => 'None', :abbr => 'None', :metric => Metric.find_by_name('None') },
              { :name => 'Degree', :abbr => 'deg', :metric => Metric.find_by_name('Incline') },
              { :name => 'Foot', :abbr => 'f', :metric => Metric.find_by_name('Distance') },
              { :name => 'Kilogram', :abbr => 'kg', :is_metric => true, :metric => Metric.find_by_name('Resistance') },
              { :name => 'Kilometer', :abbr => 'km', :is_metric => true, :metric => Metric.find_by_name('Distance') },
              { :name => 'Kilometer per Hour', :abbr => 'kph', :is_metric => true, :metric => Metric.find_by_name('Speed') },
              { :name => 'Mile', :abbr => 'mi', :metric => Metric.find_by_name('Distance') },
              { :name => 'Minute', :abbr => 'min', :metric => Metric.find_by_name('Duration') },
              { :name => 'Meter', :abbr => 'm', :is_metric => true, :metric => Metric.find_by_name('Distance') },
              { :name => 'Mile per Hour', :abbr => 'mph', :metric => Metric.find_by_name('Speed') },
              { :name => 'Pound', :abbr => 'lb', :metric => Metric.find_by_name('Resistance') },
              { :name => 'Revolution per Minute', :abbr => 'rpm', :metric => Metric.find_by_name('Cadence') },
              { :name => 'Second', :abbr => 'sec', :metric => Metric.find_by_name('Duration') },
              { :name => 'Yard', :abbr => 'y', :metric => Metric.find_by_name('Distance') },
              { :name => '25 Meter Lap', :abbr => '25m lap', :metric => Metric.find_by_name('Distance') },
              { :name => '50 Meter Lap', :abbr => '50m lap', :metric => Metric.find_by_name('Distance') },
              { :name => '250 Meter Lap', :abbr => '250m lap', :metric => Metric.find_by_name('Distance') },
              { :name => '400 Meter Lap', :abbr => '400m lap', :metric => Metric.find_by_name('Distance') }
            ])


Implement.create([
                   { :category => 'Cardio Machine', :name => 'Arm Ergometer' },
                   { :category => 'Cardio Machine', :name => 'Climber' },
                   { :category => 'Cardio Machine', :name => 'Climb Mill / Tread Wall' },
                   { :category => 'Cardio Machine', :name => 'Cycle Cross Trainer' },
                   { :category => 'Cardio Machine', :name => 'Cycle Ergometer' },
                   { :category => 'Cardio Machine', :name => 'Elliptical' },
                   { :category => 'Cardio Machine', :name => 'Elliptical Cross Trainer' },
                   { :category => 'Cardio Machine', :name => 'Kayak Machine' },
                   { :category => 'Cardio Machine', :name => 'Row Ergometer' },
                   { :category => 'Cardio Machine', :name => 'Recumbent Cycle Ergometer' },
                   { :category => 'Cardio Machine', :name => 'Recumbent Stepper' },
                   { :category => 'Cardio Machine', :name => 'Recumbent Stepper Cross Trainer' },
                   { :category => 'Cardio Machine', :name => 'Skate Machine' },
                   { :category => 'Cardio Machine', :name => 'Ski Ergometer' },
                   { :category => 'Cardio Machine', :name => 'Stair Climber' },
                   { :category => 'Cardio Machine', :name => 'Step Mill' },
                   { :category => 'Cardio Machine', :name => 'Treadmill' },
                   { :category => 'Cardio Machine', :name => 'Wave Machine' },
                   { :category => 'Equipment', :name => 'Ball' },
                   { :category => 'Equipment', :name => 'Bench' },
                   { :category => 'Equipment', :name => 'Chair' },
                   { :category => 'Equipment', :name => 'Decline Bench' },
                   { :category => 'Equipment', :name => 'Half Ball' },
                   { :category => 'Equipment', :name => 'Incline Bench' },
                   { :category => 'Equipment', :name => 'Jumprope' },
                   { :category => 'Equipment', :name => 'Medicine Ball' },
                   { :category => 'Equipment', :name => 'Power Rack' },
                   { :category => 'Equipment', :name => 'Strap' },
                   { :category => 'Equipment', :name => 'Yoga Mat' },
                   { :category => 'Sport Equipment', :name => 'Basketball' },
                   { :category => 'Sport Equipment', :name => 'Basketball Court' },
                   { :category => 'Sport Equipment', :name => 'Bicycle' },
                   { :category => 'Sport Equipment', :name => 'Box' },
                   { :category => 'Sport Equipment', :name => 'Boxing Gloves' },
                   { :category => 'Sport Equipment', :name => 'Heavy Bag' },
                   { :category => 'Sport Equipment', :name => 'Soccer Ball' },
                   { :category => 'Sport Equipment', :name => 'Soccer Field' },
                   { :category => 'Sport Equipment', :name => 'Speed Bag' },
                   { :category => 'Sport Equipment', :name => 'Swimming Pool' },
                   { :category => 'Sport Equipment', :name => 'Track' },
                   { :category => 'Sport Equipment', :name => 'Velodrome' },
                   { :category => 'Sport Equipment', :name => 'Wrist Wraps' },
                   { :category => 'Free Weight', :name => 'Barbell' },
                   { :category => 'Free Weight', :name => 'Dumbbell' },
                   { :category => 'Free Weight', :name => 'Kettlebell' },
                   { :category => 'Free Weight', :name => 'E-Z Bar' },
                   { :category => 'Free Weight', :name => 'Practice Plate' },
                   { :category => 'Resistance Machine', :name => 'Biceps Curl' },
                   { :category => 'Resistance Machine', :name => 'Back Extension' },
                   { :category => 'Resistance Machine', :name => 'Cable Row' },
                   { :category => 'Resistance Machine', :name => 'Chest Fly' },
                   { :category => 'Resistance Machine', :name => 'Chest Press' },
                   { :category => 'Resistance Machine', :name => 'Donkey Calf Raise' },
                   { :category => 'Resistance Machine', :name => 'Lat Cable Pulldown' },
                   { :category => 'Resistance Machine', :name => 'Leg Extension' },
                   { :category => 'Resistance Machine', :name => 'Leg Press' },
                   { :category => 'Resistance Machine', :name => 'Shoulder Press' },
                   { :category => 'Resistance Machine', :name => 'Side Lateral Raise' },
                   { :category => 'Resistance Machine', :name => 'Single Leg Hamstring Curl' },
                   { :category => 'Resistance Machine', :name => 'Seated Hamstring Curl' },
                   { :category => 'Resistance Machine', :name => 'Prone Hamstring Curl' },
                   { :category => 'Resistance Machine', :name => 'Plate Loaded Calf Raise' },
                   { :category => 'Resistance Machine', :name => 'Rear Deltoid Fly' },
                   { :category => 'Resistance Machine', :name => 'Seated Abductor' },
                   { :category => 'Resistance Machine', :name => 'Seated Adductor' },
                   { :category => 'Resistance Machine', :name => 'Seated Cable Row' },
                   { :category => 'Resistance Machine', :name => 'Seated Calf Press' },
                   { :category => 'Resistance Machine', :name => 'Smith' },
                   { :category => 'Resistance Machine', :name => 'Standing Calf Raise' },
                   { :category => 'Resistance Machine', :name => 'Triceps Extension' },
                   { :category => 'Resistance Machine', :name => 'Triceps Pressdown' }
                  ])

BodyPart.create([
                  { :region => 'Abdomen', :name => 'External Oblique' },
                  { :region => 'Abdomen', :name => 'Internal Oblique' },
                  { :region => 'Abdomen', :name => 'Psoas Major' },
                  { :region => 'Abdomen', :name => 'Psoas Minor' },
                  { :region => 'Abdomen', :name => 'Rectus Abdominis' },
                  { :region => 'Abdomen', :name => 'Transverse Abdominis' },
                  { :region => 'Back', :name => 'Erector Spinae' },
                  { :region => 'Back', :name => 'Infraspinatus' },
                  { :region => 'Back', :name => 'Iliocostalis Lumborum' },
                  { :region => 'Back', :name => 'Iliocostalis Thoracis' },
                  { :region => 'Back', :name => 'Latissimus Dorsi' },
                  { :region => 'Back', :name => 'Longissimus Thoracis' },
                  { :region => 'Back', :name => 'Lower Trapezius' },
                  { :region => 'Back', :name => 'Lumbrosacral' },
                  { :region => 'Back', :name => 'Middle Trapezius' },
                  { :region => 'Back', :name => 'Rhomboid Major' },
                  { :region => 'Back', :name => 'Rhomboid Minor' },
                  { :region => 'Back', :name => 'Quadratus Lumborum' },
                  { :region => 'Back', :name => 'Spinalis Thoracis' },
                  { :region => 'Back', :name => 'Teres Major' },
                  { :region => 'Back', :name => 'Teres Minor' },
                  { :region => 'Back', :name => 'Trapezius' },
                  { :region => 'Back', :name => 'Upper Trapezius' },
                  { :region => 'Chest', :name => 'Pectoralis' },
                  { :region => 'Chest', :name => 'Pectoralis Major' },
                  { :region => 'Chest', :name => 'Pectoralis Minor' },
                  { :region => 'Chest', :name => 'Serratus Anterior' },
                  { :region => 'Forearm', :name => 'Anconeus' },
                  { :region => 'Forearm', :name => 'Extensor Carpi Radialis Brevis' },
                  { :region => 'Forearm', :name => 'Extensor Carpi Radialis Longus' },
                  { :region => 'Forearm', :name => 'Extensor Carpi Ulnaris' },
                  { :region => 'Forearm', :name => 'Extensor Digiti Minimi' },
                  { :region => 'Forearm', :name => 'Extensor Digitorum' },
                  { :region => 'Forearm', :name => 'Flexor Carpi Radialis' },
                  { :region => 'Forearm', :name => 'Flexor Carpi Ulnaris' },
                  { :region => 'Forearm', :name => 'Flexor Digitorum Profundis' },
                  { :region => 'Forearm', :name => 'Flexor Digitorum Superficialis' },
                  { :region => 'Forearm', :name => 'Flexor Pollicis Longus' },
                  { :region => 'Forearm', :name => 'Palmaris Longus' },
                  { :region => 'Hip', :name => 'Abductor' },
                  { :region => 'Hip', :name => 'Adductor' },
                  { :region => 'Hip', :name => 'Adductor Longus' },
                  { :region => 'Hip', :name => 'Adductor Magnus' },
                  { :region => 'Hip', :name => 'Gluteus Maximus' },
                  { :region => 'Hip', :name => 'Gluteus Medius' },
                  { :region => 'Hip', :name => 'Gluteus Minimus' },
                  { :region => 'Hip', :name => 'Gracilis' },
                  { :region => 'Hip', :name => 'Iliacus' },
                  { :region => 'Hip', :name => 'Iliopsoas' },
                  { :region => 'Hip', :name => 'Pectineus' },
                  { :region => 'Hip', :name => 'Pyramidalis' },
                  { :region => 'Hip', :name => 'Sartorius' },
                  { :region => 'Hip', :name => 'Tensor Fascia Lata' },
                  { :region => 'Lower Leg', :name => 'Calf' },
                  { :region => 'Lower Leg', :name => 'Gastrocnemius Medial Head' },
                  { :region => 'Lower Leg', :name => 'Gastrocnemius Lateral Head' },
                  { :region => 'Lower Leg', :name => 'Flexor Digitorum Longus' },
                  { :region => 'Lower Leg', :name => 'Flexor Hallucis Longus' },
                  { :region => 'Lower Leg', :name => 'Peroneus Brevis' },
                  { :region => 'Lower Leg', :name => 'Plantaris' },
                  { :region => 'Lower Leg', :name => 'Tibialis Anterior' },
                  { :region => 'Lower Leg', :name => 'Tibialis Posterior' },
                  { :region => 'Lower Leg', :name => 'Soleus' },
                  { :region => 'Neck', :name => 'Levator Scapula' },
                  { :region => 'Neck', :name => 'Splenius Capitis' },
                  { :region => 'Neck', :name => 'Sternocleidomastoid' },
                  { :region => 'Shoulder', :name => 'Coracobrachialis' },
                  { :region => 'Shoulder', :name => 'Anterior Deltoid' },
                  { :region => 'Shoulder', :name => 'Deltoid' },
                  { :region => 'Shoulder', :name => 'Middle Deltoid' },
                  { :region => 'Shoulder', :name => 'Posterior Deltoid' },
                  { :region => 'Shoulder', :name => 'Supraspinatus' },
                  { :region => 'Upper Arm', :name => 'Biceps' },
                  { :region => 'Upper Arm', :name => 'Biceps Brachii' },
                  { :region => 'Upper Arm', :name => 'Brachialis' },
                  { :region => 'Upper Arm', :name => 'Brachioradialis' },
                  { :region => 'Upper Arm', :name => 'Triceps' },
                  { :region => 'Upper Arm', :name => 'Triceps Brachii Lateral Head' },
                  { :region => 'Upper Arm', :name => 'Triceps Brachii Long Head' },
                  { :region => 'Upper Arm', :name => 'Triceps Brachii Medial Head' },
                  { :region => 'Upper Leg', :name => 'Biceps Femoris Long Head' },
                  { :region => 'Upper Leg', :name => 'Biceps Femoris Short Head' },
                  { :region => 'Upper Leg', :name => 'Hamstring' },
                  { :region => 'Upper Leg', :name => 'Quadriceps' },
                  { :region => 'Upper Leg', :name => 'Rectus Femoris' },
                  { :region => 'Upper Leg', :name => 'Semimembranosus' },
                  { :region => 'Upper Leg', :name => 'Semitendinosus' },
                  { :region => 'Upper Leg', :name => 'Vastus Intermedius' },
                  { :region => 'Upper Leg', :name => 'Vastus Lateralis' },
                  { :region => 'Upper Leg', :name => 'Vastus Medialis' }
                ])

ActivityAttribute.create([
                           { :name => 'Auxiliary Utility' },
                           { :name => 'Basic Utility' },
                           { :name => 'Power Utility' },
                           { :name => 'Compound Mechanics' },
                           { :name => 'Dynamic Contraction' },
                           { :name => 'High Impact' },
                           { :name => 'Isolated Mechanics' },
                           { :name => 'Isometric Contraction' },
                           { :name => 'Low Impact' },
                           { :name => 'Medium Impact' },
                           { :name => 'Non-Weight Bearing' },
                           { :name => 'Pulling Force' },
                           { :name => 'Pushing Force' },
                           { :name => 'Weight Bearing' }
                          ])

#Activity.create([
#                  { :name => 'Bench Press', :activity_type => ActivityType.find_by_name('Resistance') },
#                  { :name => 'Bench Press', :activity_type => ActivityType.find_by_name('Resistance') },
#                ])